### ISSUE TITLE
Usage suggestion

### ISSUE THREAD

**Issue by drslump** [ninjaaron/fast-entry_points#8]
First of all thanks for publishing this work around, the slowness of the entrypoints was driving me crazy 😄 

I'm currently integrating it in my `setup.py` simply as follows:

```py
try:
    import fastentrypoints
except ImportError:
    from setuptools.command import easy_install
    import pkg_resources   # oh the irony :)
    easy_install.main(['fastentrypoints'])
    pkg_resources.require('fastentrypoints')
    import fastentrypoint
```

It avoids having to put `fastentrypoints.py` in the project and under normal circumstances it should have no problem installing it when required.

**Comment by ninjaaron** [comment]
Thanks! I've added your code to the README for those who don't wish to vendor!

I took out your comment about the irony only because (ironically) fastentrypoints already triggers the import of pkg_resources (though not explicitly) by importing easy_install itself. In fact, every `setup.py` file imports pkg_resources in the background! You can't get out of it there! (or maybe you could set it to `None` in sys.modules? I haven't tried to see what happens in that scenario.)

But anyway, thanks again! good stuff!
